import { useState, useEffect } from "react";
import Head from "next/head";
import Table from "../componetns/table";
import Form from "../componetns/form";
import styles from "../styles/Home.module.css";

export default function Home() {
	const [data, setData] = useState([]);

	async function fetchDAta() {
		const res = await fetch("/api/hello");
		const data = await res.json();
		setData(data);
	}

	useEffect(() => {
		fetchDAta();
	}, []);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.main}>
				<Table data={data} dataUpdate={fetchDAta} />
				<Form formSubmit={fetchDAta} />
			</div>
		</>
	);
}
